"""Build the LaTeX tables of the TMLR draft from existing result files and records only.

No model is fitted and no geometry is recomputed. Every table file starts with a LaTeX comment naming its
sources. Run from anywhere with the repo venv:

    .venv/bin/python paper/tmlr/scripts/make_tables.py

Sources (read-only):
  curvature-experiment/results/ii-rank/ii_rank_*_d16.json
  notebooks/.cache/09_physics_normal_scaling_{run}.npz            (five ML4PS encoders at d=16, ViT-B at d=20)
  notebooks/.cache/scaling/arrays/scaling__{enc}__cf.npz          (ten galaxy encoders, d=16, alpha=100)
  notebooks/.cache/scaling/records/scaling__{enc}__main_xfit.jsonl
  notebooks/.cache/scaling/records/scaling__{enc}__robust.jsonl
  notebooks/.cache/qm9/records/scaling__{enc}__robust.jsonl
  notebooks/.cache/qm9/arrays/scaling__{enc}__cf.npz
"""
import glob
import json
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[3]
CACHE = REPO / "notebooks" / ".cache"
RES = REPO / "curvature-experiment" / "results"
OUT = Path(__file__).resolve().parents[1] / "tables"
OUT.mkdir(exist_ok=True)

LABELS = ["mag_r", "photo_z", "smooth_fraction", "stellar_mass"]
QLABELS = ["gap", "mu", "alpha", "cv"]
GAL = ["vit_base", "vit_large", "clip_base", "convnext_base", "dinov3_vits16", "dinov3_vits16plus",
       "dinov3_vitb16", "dinov3_vitl16", "dinov3_vith16plus", "dinov3_vit7b16"]
QM9 = ["chemberta_10m_mlm", "chemberta_77m_mlm", "chemberta_5m_mtr", "chemberta_10m_mtr", "chemberta_77m_mtr",
       "molformer_xl", "chemfm_1b", "chemfm_3b"]
NICE = {"vit_base": "ViT-B", "vit_large": "ViT-L", "clip_base": "CLIP-B", "convnext_base": "ConvNeXt-B",
        "dinov3_vits16": "DINOv3-S", "dinov3_vits16plus": "DINOv3-S+", "dinov3_vitb16": "DINOv3-B",
        "dinov3_vitl16": "DINOv3-L", "dinov3_vith16plus": "DINOv3-H+", "dinov3_vit7b16": "DINOv3-7B",
        "chemberta_10m_mlm": "ChemBERTa-10M-MLM", "chemberta_77m_mlm": "ChemBERTa-77M-MLM",
        "chemberta_5m_mtr": "ChemBERTa-5M-MTR", "chemberta_10m_mtr": "ChemBERTa-10M-MTR",
        "chemberta_77m_mtr": "ChemBERTa-77M-MTR", "molformer_xl": "MoLFormer-XL", "chemfm_1b": "ChemFM-1B",
        "chemfm_3b": "ChemFM-3B"}
TEX = lambda s: s.replace("_", r"\_")


def jl(path):
    return [json.loads(line) for line in open(path)]


def sig(cell, alpha=0.05):
    v, p = cell["partial"], cell["p"]
    s = f"${v:+.2f}$"
    return s if p < alpha else s[:-1] + "^{*}$"


def write(name, header, body):
    (OUT / name).write_text(header + body)
    print("wrote", OUT / name)


# ---------------------------------------------------------------- II spectrum (test 0)
def ii_spectrum():
    rows = []
    for enc in GAL:
        d = json.load(open(RES / "ii-rank" / f"ii_rank_{enc}_d16.json"))
        s, sp, ref = d["insphere_p25_p50_p75"], d["median_normalised_spectrum"], d["random_reference"]
        rows.append((enc, d["D"], s["erank"][1], s["pr"][1], int(s["k90"][1]), int(s["k99"][1]), s["cond"][1],
                     sp[15], sp[31], ref["erank"], ref["k90"], ref["cond"], d["verdict"]))
    head = ("% SOURCE: curvature-experiment/results/ii-rank/ii_rank_<enc>_d16.json (insphere_p25_p50_p75 medians,\n"
            "% median_normalised_spectrum[15] and [31], random_reference, verdict). Generated by\n"
            "% paper/tmlr/scripts/make_tables.py; do not edit by hand.\n")
    body = ["\\begin{tabular}{lrrrrrrrrrrl}", "\\toprule",
            " & & \\multicolumn{7}{c}{decoder $\\mathrm{II}^S$, median over 512 anchors} & \\multicolumn{2}{c}{Gaussian ref.} & \\\\",
            "\\cmidrule(lr){3-9}\\cmidrule(lr){10-11}",
            "encoder & $D$ & erank & PR & $k_{90}$ & $k_{99}$ & cond & $s_{16}/s_1$ & $s_{32}/s_1$ & erank & $k_{90}$ & rule \\\\",
            "\\midrule"]
    for r in rows:
        body.append(f"{NICE[r[0]]} & {r[1]} & {r[2]:.1f} & {r[3]:.1f} & {r[4]} & {r[5]} & {r[6]:.0f} & {r[7]:.2f} & {r[8]:.2f} & "
                    f"{r[9]:.0f} & {r[10]} & {r[12]} \\\\")
    body += ["\\bottomrule", "\\end{tabular}", ""]
    write("tab_ii_spectrum.tex", head, "\n".join(body))
    return rows


# ---------------------------------------------------------------- what the normal readout reads
def normal_readout():
    runs = [("vit_base", "d16"), ("vit_base", "d20"), ("dinov3_vitb16", "d16"), ("clip_base", "d16"),
            ("convnext_base", "d16"), ("vit_large", "d16")]
    full, summary = [], []
    for enc, dd in runs:
        z = np.load(CACHE / f"09_physics_normal_scaling_{enc}_{dd}.npz")
        per = []
        for lab in LABELS:
            ratio = np.sqrt(z[f"{lab}:S_model:qq"] / z[f"{lab}:S:qq"])
            tS, tM = z[f"{lab}:S:t_star"], z[f"{lab}:S_model:t_star"]
            rS, rM = z[f"{lab}:random_qmatched:dR2"], None
            per.append(dict(lab=lab, ratio=np.median(ratio), share=np.median(ratio ** 2), tS=np.median(tS), tS1=np.mean(tS > 1),
                            hS=np.mean(z[f"{lab}:S:dR2"] > 0), hM=np.mean(z[f"{lab}:S_model:dR2"] > 0), tM=np.median(tM),
                            hR=np.mean(rS > 0), dS=np.median(z[f"{lab}:S:dR2"]), dM=np.median(z[f"{lab}:S_model:dR2"])))
        full.append((enc, dd, per))
    head = ("% SOURCE: notebooks/.cache/09_physics_normal_scaling_<enc>_<d>.npz (alpha = 100, 512 anchors, k = 2048).\n"
            "% ||q||/||p|| = sqrt(<lab>:S_model:qq / <lab>:S:qq) per anchor (qq is the centred sum of squares of the scaled\n"
            "% term: p = X w_S for variant S, q = (1/2)<w_S,II^S>(u,u) for S_model), median over anchors.\n"
            "% t*_S, t*_model = <lab>:S:t_star, <lab>:S_model:t_star; help = fraction of anchors with dR2 > 0.\n"
            "% Generated by paper/tmlr/scripts/make_tables.py.\n")
    body = ["\\begin{tabular}{llccccccccc}", "\\toprule",
            " & & & & \\multicolumn{3}{c}{data-side $S$ (scales $p$)} & \\multicolumn{3}{c}{decoder $S_{\\mathrm{model}}$ (scales $q$)} & random \\\\",
            "\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}\\cmidrule(lr){11-11}",
            "run & label & $\\norm{q}/\\norm{p}$ & $\\norm{q}^2/\\norm{p}^2$ & help & $\\Delta R^2(1)$ & $t^*_S$ ($>1$) & help & $\\Delta R^2(1)$ & $t^*_{\\mathrm{model}}$ & help \\\\",
            "\\midrule"]
    for enc, dd, per in full:
        for i, p in enumerate(per):
            run = f"{NICE[enc]}, $d={dd[1:]}$" if i == 0 else ""
            body.append(f"{run} & {TEX(p['lab'])} & {p['ratio']:.2f} & {p['share']:.2f} & {p['hS']:.2f} & ${p['dS']:+.3f}$ & {p['tS']:.2f} ({p['tS1']:.2f}) & "
                        f"{p['hM']:.2f} & ${p['dM']:+.3f}$ & {p['tM']:.2f} & {p['hR']:.2f} \\\\")
        body.append("\\addlinespace[2pt]")
    body += ["\\bottomrule", "\\end{tabular}", ""]
    write("tab_normal_readout_full.tex", head, "\n".join(body))

    # ten-encoder extension from the scaling arrays (same runner, sweep geometry)
    ten = []
    for enc in GAL:
        z = np.load(CACHE / "scaling" / "arrays" / f"scaling__{enc}__cf.npz")
        rr = [np.median(np.sqrt(z[f"{lab}:S_model:qq"] / z[f"{lab}:S:qq"])) for lab in LABELS]
        ts = [np.median(z[f"{lab}:S:t_star"]) for lab in LABELS]
        hs = [np.mean(z[f"{lab}:S:dR2"] > 0) for lab in LABELS]
        ten.append((enc, min(rr), max(rr), min(ts), max(ts), min(hs), max(hs)))
    head2 = ("% SOURCE: notebooks/.cache/scaling/arrays/scaling__<enc>__cf.npz (ten galaxy encoders, d = 16, alpha = 100),\n"
             "% same definitions as tab_normal_readout_full.tex; ranges are over the four labels.\n"
             "% Generated by paper/tmlr/scripts/make_tables.py.\n")
    body2 = ["\\begin{tabular}{lccc}", "\\toprule",
             "encoder & median $\\norm{q}/\\norm{p}$ & median $t^*_S$ & help ($S$) \\\\", "\\midrule"]
    for e in ten:
        body2.append(f"{NICE[e[0]]} & {e[1]:.2f}--{e[2]:.2f} & {e[3]:.2f}--{e[4]:.2f} & {e[5]:.2f}--{e[6]:.2f} \\\\")
    body2 += ["\\bottomrule", "\\end{tabular}", ""]
    write("tab_normal_readout_ten.tex", head2, "\n".join(body2))
    return full, ten


# ---------------------------------------------------------------- diagnostic: emp vs dec vs |Hess y|
def diagnostic():
    rows = []
    for enc in GAL:
        recs = jl(CACHE / "scaling" / "records" / f"scaling__{enc}__main_xfit.jsonl")
        res = {r["label"]: r for r in recs if r["row"] == "result"}
        xf = {r["label"]: r for r in recs if r["row"] == "xfit"}
        rob = jl(CACHE / "scaling" / "records" / f"scaling__{enc}__robust.jsonl")
        rob = {(r["label"], r["alpha_mode"]): r for r in rob if r["row"] == "result"}
        for lab in LABELS:
            c = res[lab]["columns"]
            x = xf[lab]["columns"]
            b100 = rob[(lab, "published")]["bootstrap"]["32"]
            bst = rob[(lab, "tuned")]["bootstrap"]["32"]
            rows.append(dict(enc=enc, lab=lab, emp=c["hess_mismatch_emp"]["multiscale"], dec=c["hess_mismatch_dec"]["multiscale"],
                             hy=c["hess_label"]["multiscale"], align=c["align_cos_tan"]["multiscale"],
                             xdec=x["hess_mismatch_dec"]["fitA_scoreB"], xhy=x["hess_label"]["fitA_scoreB"],
                             b_emp100=b100["hess_mismatch_emp"]["excludes_zero"], b_empst=bst["hess_mismatch_emp"]["excludes_zero"],
                             b_al100=b100["align_cos_tan"]["excludes_zero"], b_alst=bst["align_cos_tan"]["excludes_zero"]))
    head = ("% SOURCE: notebooks/.cache/scaling/records/scaling__<enc>__main_xfit.jsonl, rows 'result' (columns\n"
            "% hess_mismatch_emp, hess_mismatch_dec, hess_label, align_cos_tan; key 'multiscale') and rows 'xfit'\n"
            "% (hess_mismatch_dec and hess_label, fitA_scoreB); bootstrap flags from scaling__<enc>__robust.jsonl,\n"
            "% bootstrap['32'][col]['excludes_zero'], alpha_mode published (alpha=100) and tuned (alpha*).\n"
            "% NOTE: the cross-fit 'mismatch' columns of the ML4PS appendix (Tables B and C there) are hess_mismatch_dec\n"
            "% (the xfit rows store only dec, align and hess_label), while its main-table mismatch is hess_mismatch_emp.\n"
            "% The sanity review says every real-data table uses emp; the records say the cross-fit tables use dec.\n"
            "% Generated by paper/tmlr/scripts/make_tables.py.\n")
    body = ["\\begin{tabular}{llcccccccc}", "\\toprule",
            " & & \\multicolumn{4}{c}{multi-scale partial, $\\alpha=100$} & \\multicolumn{2}{c}{cross-fit (A$\\to$B)} & \\multicolumn{2}{c}{boot.\\ CI excl.\\ 0, emp} \\\\",
            "\\cmidrule(lr){3-6}\\cmidrule(lr){7-8}\\cmidrule(lr){9-10}",
            "encoder & label & emp & dec & $\\norm{\\operatorname{Hess}_M y}_g$ & align & dec & $\\norm{\\operatorname{Hess}_M y}_g$ & $\\alpha=100$ & $\\alpha^*$ \\\\",
            "\\midrule"]
    yn = lambda b: "y" if b else "n"
    for i, r in enumerate(rows):
        enc = NICE[r["enc"]] if r["lab"] == "mag_r" else ""
        body.append(f"{enc} & {TEX(r['lab'])} & {sig(r['emp'])} & {sig(r['dec'])} & {sig(r['hy'])} & {sig(r['align'])} & "
                    f"{sig(r['xdec'])} & {sig(r['xhy'])} & {yn(r['b_emp100'])} & {yn(r['b_empst'])} \\\\")
        if r["lab"] == "stellar_mass":
            body.append("\\addlinespace[2pt]")
    body += ["\\bottomrule", "\\end{tabular}", ""]
    write("tab_diag_full.tex", head, "\n".join(body))

    # summary counts
    gap = np.array([abs(r["emp"]["partial"] - r["hy"]["partial"]) for r in rows])
    gapd = np.array([abs(r["dec"]["partial"] - r["hy"]["partial"]) for r in rows])
    gaped = np.array([abs(r["emp"]["partial"] - r["dec"]["partial"]) for r in rows])
    stats = dict(n=len(rows), le05=int((gap <= 0.05).sum()), le03=int((gap <= 0.03).sum()), med=float(np.median(gap)),
                 maxgap=float(gap.max()), dec_le05=int((gapd <= 0.05).sum()), dec_med=float(np.median(gapd)),
                 empdec_max=float(gaped.max()), empdec_med=float(np.median(gaped)))
    cnt = {}
    for lab in LABELS:
        rr = [r for r in rows if r["lab"] == lab]
        cnt[lab] = dict(emp100=sum(r["b_emp100"] for r in rr), empst=sum(r["b_empst"] for r in rr),
                        al100=sum(r["b_al100"] for r in rr), alst=sum(r["b_alst"] for r in rr))
    head3 = ("% SOURCE: notebooks/.cache/scaling/records/scaling__<enc>__robust.jsonl (32-block bootstrap, 2000 resamples,\n"
             "% excludes_zero), ten galaxy encoders. Counts are encoders (of 10) whose 95% interval excludes zero.\n"
             "% Generated by paper/tmlr/scripts/make_tables.py.\n")
    body3 = ["\\begin{tabular}{lcccc}", "\\toprule",
             " & \\multicolumn{2}{c}{residual-quadratic mismatch (emp)} & \\multicolumn{2}{c}{alignment} \\\\",
             "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}",
             "label & $\\alpha=100$ & $\\alpha^*$ & $\\alpha=100$ & $\\alpha^*$ \\\\", "\\midrule"]
    for lab in LABELS:
        c = cnt[lab]
        body3.append(f"{TEX(lab)} & {c['emp100']}/10 & {c['empst']}/10 & {c['al100']}/10 & {c['alst']}/10 \\\\")
    body3 += ["\\bottomrule", "\\end{tabular}", ""]
    write("tab_boot_counts.tex", head3, "\n".join(body3))
    return rows, stats, cnt


# ---------------------------------------------------------------- QM9
def qm9():
    rows = []
    for enc in QM9:
        rob = jl(CACHE / "qm9" / "records" / f"scaling__{enc}__robust.jsonl")
        rob = {(r["label"], r["alpha_mode"]): r for r in rob if r["row"] == "result"}
        z = np.load(CACHE / "qm9" / "arrays" / f"scaling__{enc}__cf.npz")
        for lab in QLABELS:
            a, t = rob[(lab, "published")], rob[(lab, "tuned")]
            rows.append(dict(enc=enc, lab=lab, r2a=a["global_oof_r2"], r2t=t["global_oof_r2"], ast=t["alpha"],
                             mis=a["partials"]["published_controls"]["hess_mismatch_emp"],
                             misst=t["partials"]["published_controls"]["hess_mismatch_emp"],
                             ba=a["bootstrap"]["32"]["hess_mismatch_emp"]["excludes_zero"],
                             bt=t["bootstrap"]["32"]["hess_mismatch_emp"]["excludes_zero"],
                             ha=a["cf"]["S_model"]["help"], ht=t["cf"]["S_model"]["help"],
                             ta=a["cf"]["S_model"]["t_star"], tt=t["cf"]["S_model"]["t_star"],
                             sur=a["surrogate"]["spearman"], hS=float(np.mean(z[f"{lab}:S:dR2"] > 0)),
                             qp=float(np.median(np.sqrt(z[f"{lab}:S_model:qq"] / z[f"{lab}:S:qq"]))),
                             ho=a["heldout"]["median"], hot=t["heldout"]["median"]))
    head = ("% SOURCE: notebooks/.cache/qm9/records/scaling__<enc>__robust.jsonl (rows 'result', alpha_mode published\n"
            "% = alpha 100 and tuned = alpha*; global_oof_r2, partials.published_controls.hess_mismatch_emp (permutation p),\n"
            "% bootstrap['32'] excludes_zero, cf.S_model help and t_star, surrogate.spearman); help of the data-side\n"
            "% variant S and ||q||/||p|| from notebooks/.cache/qm9/arrays/scaling__<enc>__cf.npz (alpha = 100).\n"
            "% Generated by paper/tmlr/scripts/make_tables.py.\n")
    body = ["\\begin{tabular}{llcccccccccc}", "\\toprule",
            " & & \\multicolumn{2}{c}{OOF $R^2$} & \\multicolumn{2}{c}{mismatch (emp)} & \\multicolumn{2}{c}{help $S_{\\mathrm{model}}$} & \\multicolumn{2}{c}{$t^*_{\\mathrm{model}}$} & & \\\\",
            "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\\cmidrule(lr){7-8}\\cmidrule(lr){9-10}",
            "encoder & label & $100$ & $\\alpha^*$ & $100$ & $\\alpha^*$ & $100$ & $\\alpha^*$ & $100$ & $\\alpha^*$ & $\\rho_{\\mathrm{sur}}$ & help $S$ \\\\",
            "\\midrule"]
    mark = lambda cell, boot: sig(cell) + ("$^\\dagger$" if boot else "")
    for r in rows:
        enc = NICE[r["enc"]] if r["lab"] == "gap" else ""
        body.append(f"{enc} & {r['lab']} & {r['r2a']:.2f} & {r['r2t']:.2f} & {mark(r['mis'], r['ba'])} & {mark(r['misst'], r['bt'])} & "
                    f"{r['ha']:.2f} & {r['ht']:.2f} & {r['ta']:.2f} & {r['tt']:.2f} & ${r['sur']:+.2f}$ & {r['hS']:.2f} \\\\")
        if r["lab"] == "cv":
            body.append("\\addlinespace[2pt]")
    body += ["\\bottomrule", "\\end{tabular}", ""]
    write("tab_qm9_full.tex", head, "\n".join(body))
    return rows


if __name__ == "__main__":
    ii = ii_spectrum()
    full, ten = normal_readout()
    drows, dstats, dcnt = diagnostic()
    qrows = qm9()
    print("\n== summary numbers for the text ==")
    er = [r[2] for r in ii]; k90 = [r[4] for r in ii]; cond = [r[6] for r in ii]
    print(f"II: erank {min(er):.1f}-{max(er):.1f}; k90 {min(k90)}-{max(k90)}; cond {min(cond):.0f}-{max(cond):.0f}; "
          f"pr {min(r[3] for r in ii):.1f}-{max(r[3] for r in ii):.1f}; k99 {min(r[5] for r in ii)}-{max(r[5] for r in ii)}; "
          f"s16 {min(r[7] for r in ii):.2f}-{max(r[7] for r in ii):.2f}; s32 {min(r[8] for r in ii):.2f}-{max(r[8] for r in ii):.2f}; "
          f"ref erank {min(r[9] for r in ii):.0f}-{max(r[9] for r in ii):.0f}; ref cond {min(r[11] for r in ii):.1f}-{max(r[11] for r in ii):.1f}")
    allp = [p for _, _, per in full for p in per]
    print("q/p (6 runs): %.3f-%.3f; share %.3f-%.3f; t*_S %.2f-%.2f; t*_S>1 %.2f-%.2f; help S %.3f-%.3f; help M %.3f-%.3f; t*_M %.2f-%.2f; dR2 S %.3f-%.3f; dR2 M %.3f-%.3f" % (
        min(p['ratio'] for p in allp), max(p['ratio'] for p in allp), min(p['share'] for p in allp), max(p['share'] for p in allp),
        min(p['tS'] for p in allp), max(p['tS'] for p in allp), min(p['tS1'] for p in allp), max(p['tS1'] for p in allp),
        min(p['hS'] for p in allp), max(p['hS'] for p in allp), min(p['hM'] for p in allp), max(p['hM'] for p in allp),
        min(p['tM'] for p in allp), max(p['tM'] for p in allp), min(p['dS'] for p in allp), max(p['dS'] for p in allp),
        min(p['dM'] for p in allp), max(p['dM'] for p in allp)))
    print("q/p (10 enc): %.2f-%.2f; t*_S %.2f-%.2f; help S %.2f-%.2f" % (min(e[1] for e in ten), max(e[2] for e in ten),
          min(e[3] for e in ten), max(e[4] for e in ten), min(e[5] for e in ten), max(e[6] for e in ten)))
    print("diag:", dstats)
    print("boot counts:", dcnt)
    for key in ("r2a", "r2t", "ha", "ht", "ta", "tt", "sur", "hS", "qp", "ho", "hot"):
        v = [r[key] for r in qrows]
        print(f"qm9 {key}: {min(v):.3f}-{max(v):.3f}")
    fm = [r for r in qrows if r["enc"].startswith("chemfm")]
    print("chemfm r2 @100 %.2f-%.2f, tuned %.2f-%.2f" % (min(r['r2a'] for r in fm), max(r['r2a'] for r in fm), min(r['r2t'] for r in fm), max(r['r2t'] for r in fm)))
    for r in fm:
        print(r["enc"], r["lab"], "mis100 %+.3f p %.3f boot %s | tuned %+.3f p %.3f boot %s | ho %.3f/%.3f" % (
            r['mis']['partial'], r['mis']['p'], r['ba'], r['misst']['partial'], r['misst']['p'], r['bt'], r['ho'], r['hot']))
    cb = [r for r in qrows if r["enc"].startswith("chemberta")]
    print("chemberta tuned help %.2f-%.2f" % (min(r['ht'] for r in cb), max(r['ht'] for r in cb)))
    mf = [r for r in qrows if r["enc"].startswith("molformer")]
    print("molformer tuned help %.2f-%.2f" % (min(r['ht'] for r in mf), max(r['ht'] for r in mf)))
    print("chemfm tuned help %.2f-%.2f" % (min(r['ht'] for r in fm), max(r['ht'] for r in fm)))
    print("qm9 boot mism alpha100 per label:", {l: sum(r['ba'] for r in qrows if r['lab'] == l) for l in QLABELS},
          "tuned:", {l: sum(r['bt'] for r in qrows if r['lab'] == l) for l in QLABELS})
    print("qm9 alpha* values:", sorted(set(r['ast'] for r in qrows)), "at 0.001:", sum(r['ast'] == 0.001 for r in qrows), "of", len(qrows))


# ---------------------------------------------------------------- copies of report tables (tabular body only)
def copy_report_tabular(src_name, dst_name, replace=()):
    src = RES / "scaling" / src_name
    t = src.read_text()
    body = t[t.index("\\begin{tabular}"): t.index("\\end{tabular}") + len("\\end{tabular}")]
    for a, b in replace:
        body = body.replace(a, b)
    head = (f"% SOURCE: curvature-experiment/results/scaling/{src_name} (tabular body copied verbatim by\n"
            "% paper/tmlr/scripts/make_tables.py; only header labels renamed: " + "; ".join(f"'{a}' -> '{b}'" for a, b in replace) + ").\n")
    (OUT / dst_name).write_text(head + body + "\n")
    print("wrote", OUT / dst_name)


if __name__ == "__main__":
    copy_report_tabular("tab_scaling_cf.tex", "tab_scaling_cf_body.tex",
                        replace=(("model normal $S$", "decoder $S_{\\mathrm{model}}$"),))
    copy_report_tabular("tab_scaling_robust.tex", "tab_scaling_robust_body.tex")
